#Eureka Server port
server:
  port: 1111
  
#Application Name
spring:
  application:
    name: eureka
    
#Config Server config
  config:
    import: optioneal:configserver:http://localhost:2222  #where the config-service is running

#Eureka client configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
    