#Events service port
server:
  port: 7777
spring:
  #Application Name
  application:
    name: event
  #Config Server configuration data
  config: 
    import: optional:configserver:http://localhost:2222
  #Datasource config database access
  datasource:
    url: jdbc:mysql://10.80.148.154:3306/eventsdb
    username: root
    password: root
  #Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update