server:
  port: 3333
spring:
  cloud:
   gateway:
    routes:
      - id: user
        uri: lb://USER
        predicates: Path=/api/v1/users/**
      - id: event
        uri: lb://EVENT
        predicates: Path=/api/v1/events/**
      - id: purchase
        uri: lb://PURCHASE
        predicates: Path=/api/v1/payments/**
      - id: purchase
        uri: lb://PURCHASE
        predicates: Path=/api/v1/tickets/**

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
