server:
  port: 9999
spring:
  application:
    name: purchase
  datasource:
    url: jdbc:mysql://10.80.148.154:3306/ticketsdb
    #url: jdbc:mysql://localhost:3306/ticketsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
